import type { VisoraEvent } from '../../core/models/event.model';

export const MOCK_EVENTS: VisoraEvent[] = [
  {
    id: 'evt-001',
    cameraId: 'cam-001',
    cameraName: 'Cámara Entrada Principal',
    storeId: 'store-001',
    storeName: 'Tienda Miraflores',
    location: 'Entrada principal',
    severity: 'critical',
    type: 'weapon_detection',
    status: 'pending',
    description: 'Objeto cortante detectado en zona de entrada. Alta confianza de detección.',
    timestamp: '2026-06-11T14:32:07',
    evidence: [
      { id: 'ev-001a', type: 'image', label: 'Fotograma 14:32:07' },
      { id: 'ev-001b', type: 'video', label: 'Clip 30s', durationSeconds: 30 },
    ],
    detection: {
      confidence: 0.94,
      objectType: 'Objeto cortante',
      boundingBox: { x: 120, y: 80, width: 60, height: 90 },
    },
    recommendedActions: [
      { label: 'Alertar a seguridad inmediatamente', icon: 'warning', severity: 'critical' },
      { label: 'Revisar video completo', icon: 'videocam', severity: 'suspicious' },
      { label: 'Generar reporte de incidente', icon: 'description', severity: 'normal' },
    ],
  },
  {
    id: 'evt-002',
    cameraId: 'cam-005',
    cameraName: 'Cámara Sala Principal',
    storeId: 'store-002',
    storeName: 'Tienda San Isidro',
    location: 'Sala de ventas',
    severity: 'suspicious',
    type: 'facial_recognition',
    status: 'pending',
    description: 'Reconocimiento facial: persona identificada en lista de seguimiento.',
    timestamp: '2026-06-11T14:28:45',
    evidence: [
      { id: 'ev-002a', type: 'image', label: 'Fotograma 14:28:45' },
    ],
    detection: {
      confidence: 0.87,
      personId: 'P-2041',
      personLabel: 'Persona en lista de seguimiento',
      boundingBox: { x: 200, y: 60, width: 80, height: 120 },
    },
    recommendedActions: [
      { label: 'Notificar a supervisor de tienda', icon: 'person', severity: 'suspicious' },
      { label: 'Monitorear movimiento en tiempo real', icon: 'visibility', severity: 'suspicious' },
    ],
    notes: 'Identificación no concluyente. Requiere revisión manual.',
  },
  {
    id: 'evt-003',
    cameraId: 'cam-009',
    cameraName: 'Cámara Interior A',
    storeId: 'store-005',
    storeName: 'Tienda Barranco',
    location: 'Pasillo central',
    severity: 'suspicious',
    type: 'suspicious_activity',
    status: 'reviewed',
    description: 'Aglomeración inusual de personas detectada. Comportamiento atípico registrado.',
    timestamp: '2026-06-11T14:20:00',
    evidence: [
      { id: 'ev-003a', type: 'image', label: 'Fotograma 14:20:00' },
      { id: 'ev-003b', type: 'video', label: 'Clip 45s', durationSeconds: 45 },
    ],
    detection: {
      confidence: 0.78,
      objectType: 'Grupo de personas',
    },
    recommendedActions: [
      { label: 'Revisar contexto del evento', icon: 'search', severity: 'normal' },
    ],
  },
  {
    id: 'evt-004',
    cameraId: 'cam-002',
    cameraName: 'Cámara Caja Registradora',
    storeId: 'store-001',
    storeName: 'Tienda Miraflores',
    location: 'Zona de cajas',
    severity: 'normal',
    type: 'facial_recognition',
    status: 'reviewed',
    description: 'Reconocimiento facial completado. Persona no registrada en ninguna lista.',
    timestamp: '2026-06-11T14:15:30',
    evidence: [
      { id: 'ev-004a', type: 'image', label: 'Fotograma 14:15:30' },
    ],
    detection: {
      confidence: 0.91,
      personLabel: 'Persona no registrada',
      boundingBox: { x: 150, y: 70, width: 75, height: 115 },
    },
    recommendedActions: [
      { label: 'Registrar como cliente frecuente', icon: 'person_add', severity: 'normal' },
    ],
  },
  {
    id: 'evt-005',
    cameraId: 'cam-004',
    cameraName: 'Cámara Entrada Sur',
    storeId: 'store-002',
    storeName: 'Tienda San Isidro',
    location: 'Entrada lateral sur',
    severity: 'critical',
    type: 'suspicious_activity',
    status: 'pending',
    description: 'Movimiento detectado fuera de horario comercial. Posible intrusión.',
    timestamp: '2026-06-11T02:47:15',
    evidence: [
      { id: 'ev-005a', type: 'image', label: 'Fotograma 02:47:15' },
      { id: 'ev-005b', type: 'video', label: 'Clip 60s', durationSeconds: 60 },
    ],
    detection: {
      confidence: 0.96,
      objectType: 'Movimiento humano',
    },
    recommendedActions: [
      { label: 'Contactar a policía inmediatamente', icon: 'local_police', severity: 'critical' },
      { label: 'Activar alarma de seguridad', icon: 'alarm', severity: 'critical' },
      { label: 'Notificar al propietario', icon: 'phone', severity: 'suspicious' },
    ],
  },
  {
    id: 'evt-006',
    cameraId: 'cam-008',
    cameraName: 'Cámara Frente de Tienda',
    storeId: 'store-004',
    storeName: 'Tienda Callao',
    location: 'Fachada exterior',
    severity: 'normal',
    type: 'system',
    status: 'dismissed',
    description: 'Verificación periódica del sistema. Todos los sistemas operativos.',
    timestamp: '2026-06-11T13:00:00',
    evidence: [],
    detection: { confidence: 1.0 },
    recommendedActions: [],
    notes: 'Evento automático del sistema. Sin acción requerida.',
  },
  {
    id: 'evt-007',
    cameraId: 'cam-010',
    cameraName: 'Cámara Interior B',
    storeId: 'store-005',
    storeName: 'Tienda Barranco',
    location: 'Zona premium',
    severity: 'suspicious',
    type: 'facial_recognition',
    status: 'pending',
    description: 'Rostro parcialmente cubierto. Sistema no pudo completar identificación.',
    timestamp: '2026-06-11T13:55:22',
    evidence: [
      { id: 'ev-007a', type: 'image', label: 'Fotograma 13:55:22' },
    ],
    detection: {
      confidence: 0.42,
      personLabel: 'Identificación fallida — rostro cubierto',
    },
    recommendedActions: [
      { label: 'Revisar video manualmente', icon: 'videocam', severity: 'suspicious' },
      { label: 'Solicitar identificación en caja', icon: 'badge', severity: 'normal' },
    ],
  },
  {
    id: 'evt-008',
    cameraId: 'cam-012',
    cameraName: 'Cámara Bodega',
    storeId: 'store-007',
    storeName: 'Tienda Chorrillos',
    location: 'Bodega trasera',
    severity: 'suspicious',
    type: 'weapon_detection',
    status: 'reviewed',
    description: 'Posible objeto contundente detectado. Confianza media.',
    timestamp: '2026-06-11T11:42:08',
    evidence: [
      { id: 'ev-008a', type: 'image', label: 'Fotograma 11:42:08' },
      { id: 'ev-008b', type: 'video', label: 'Clip 20s', durationSeconds: 20 },
    ],
    detection: {
      confidence: 0.61,
      objectType: 'Objeto contundente (posible)',
      boundingBox: { x: 90, y: 110, width: 50, height: 70 },
    },
    recommendedActions: [
      { label: 'Verificar con supervisor', icon: 'person', severity: 'suspicious' },
    ],
    notes: 'Revisado el 2026-06-11 12:00. Resultado: herramienta de trabajo.',
  },
  {
    id: 'evt-009',
    cameraId: 'cam-001',
    cameraName: 'Cámara Entrada Principal',
    storeId: 'store-001',
    storeName: 'Tienda Miraflores',
    location: 'Entrada principal',
    severity: 'normal',
    type: 'facial_recognition',
    status: 'reviewed',
    description: 'Reconocimiento de empleado registrado. Acceso autorizado.',
    timestamp: '2026-06-11T09:05:11',
    evidence: [
      { id: 'ev-009a', type: 'image', label: 'Fotograma 09:05:11' },
    ],
    detection: {
      confidence: 0.98,
      personId: 'EMP-015',
      personLabel: 'Empleado autorizado',
      boundingBox: { x: 180, y: 55, width: 85, height: 130 },
    },
    recommendedActions: [],
  },
  {
    id: 'evt-010',
    cameraId: 'cam-005',
    cameraName: 'Cámara Sala Principal',
    storeId: 'store-002',
    storeName: 'Tienda San Isidro',
    location: 'Sala de ventas',
    severity: 'critical',
    type: 'suspicious_activity',
    status: 'pending',
    description: 'Persona esquivando cámaras de forma sistemática. Comportamiento evasivo crítico.',
    timestamp: '2026-06-11T16:10:33',
    evidence: [
      { id: 'ev-010a', type: 'image', label: 'Fotograma 16:10:33' },
      { id: 'ev-010b', type: 'video', label: 'Clip 90s', durationSeconds: 90 },
    ],
    detection: {
      confidence: 0.89,
      objectType: 'Comportamiento evasivo',
    },
    recommendedActions: [
      { label: 'Alertar a seguridad en piso', icon: 'security', severity: 'critical' },
      { label: 'Activar seguimiento multi-cámara', icon: 'videocam', severity: 'suspicious' },
      { label: 'Generar reporte', icon: 'description', severity: 'normal' },
    ],
  },
  {
    id: 'evt-011',
    cameraId: 'cam-004',
    cameraName: 'Cámara Entrada Sur',
    storeId: 'store-002',
    storeName: 'Tienda San Isidro',
    location: 'Entrada lateral sur',
    severity: 'normal',
    type: 'system',
    status: 'dismissed',
    description: 'Reinicio automático de cámara completado correctamente.',
    timestamp: '2026-06-11T08:00:00',
    evidence: [],
    detection: { confidence: 1.0 },
    recommendedActions: [],
  },
  {
    id: 'evt-012',
    cameraId: 'cam-009',
    cameraName: 'Cámara Interior A',
    storeId: 'store-005',
    storeName: 'Tienda Barranco',
    location: 'Pasillo central',
    severity: 'suspicious',
    type: 'suspicious_activity',
    status: 'pending',
    description: 'Cliente permanece estático en zona de alta rotación por más de 15 minutos.',
    timestamp: '2026-06-11T15:45:00',
    evidence: [
      { id: 'ev-012a', type: 'image', label: 'Fotograma 15:45:00' },
    ],
    detection: {
      confidence: 0.73,
      objectType: 'Persona estática prolongada',
    },
    recommendedActions: [
      { label: 'Asignar empleado para atención', icon: 'person', severity: 'normal' },
      { label: 'Monitorear comportamiento', icon: 'visibility', severity: 'suspicious' },
    ],
  },
];
