import type { Alert } from '../../core/models/alert.model';

export const MOCK_ALERTS: Alert[] = [
  {
    id: 'alert-001',
    eventId: 'evt-001',
    eventType: 'weapon_detection',
    cameraId: 'cam-001',
    cameraName: 'Cámara Entrada Principal',
    storeId: 'store-001',
    storeName: 'Tienda Miraflores',
    location: 'Entrada principal',
    severity: 'critical',
    status: 'open',
    leida: false,
    title: 'Objeto peligroso detectado en entrada',
    description: 'El sistema detectó con alta confianza un objeto cortante en la zona de entrada principal. Se requiere intervención inmediata.',
    createdAt: '2026-06-11T14:32:07',
    assignedTo: 'Jefe de Seguridad',
    evidence: [
      { id: 'ae-001a', type: 'image', label: 'Fotograma 14:32:07' },
      { id: 'ae-001b', type: 'video', label: 'Clip 30s', durationSeconds: 30 },
    ],
    timeline: [
      { timestamp: '2026-06-11T14:32:07', action: 'Alerta generada automáticamente por detección de arma', actor: 'Sistema VISORA', icon: 'notifications' },
      { timestamp: '2026-06-11T14:32:10', action: 'Notificación enviada a Jefe de Seguridad', actor: 'Sistema VISORA', icon: 'send' },
      { timestamp: '2026-06-11T14:32:55', action: 'Alerta escalada — criticidad confirmada', actor: 'Sistema VISORA', icon: 'warning' },
    ],
    recommendedActions: [
      { label: 'Alertar a seguridad inmediatamente', icon: 'warning', severity: 'critical' },
      { label: 'Revisar video completo del evento', icon: 'videocam', severity: 'suspicious' },
      { label: 'Generar reporte de incidente', icon: 'description', severity: 'normal' },
    ],
  },
  {
    id: 'alert-002',
    eventId: 'evt-002',
    eventType: 'facial_recognition',
    cameraId: 'cam-005',
    cameraName: 'Cámara Sala Principal',
    storeId: 'store-002',
    storeName: 'Tienda San Isidro',
    location: 'Sala de ventas',
    severity: 'suspicious',
    status: 'open',
    leida: false,
    title: 'Persona en lista de seguimiento identificada',
    description: 'El sistema de reconocimiento facial identificó a una persona registrada en la lista de seguimiento interno. Confianza del 87%.',
    createdAt: '2026-06-11T14:28:45',
    assignedTo: 'Supervisor Torres',
    evidence: [
      { id: 'ae-002a', type: 'image', label: 'Fotograma 14:28:45' },
    ],
    timeline: [
      { timestamp: '2026-06-11T14:28:45', action: 'Alerta generada por reconocimiento facial', actor: 'Sistema VISORA', icon: 'notifications' },
      { timestamp: '2026-06-11T14:28:48', action: 'Notificación enviada a Supervisor Torres', actor: 'Sistema VISORA', icon: 'send' },
    ],
    recommendedActions: [
      { label: 'Notificar a supervisor de tienda', icon: 'person', severity: 'suspicious' },
      { label: 'Monitorear movimiento en tiempo real', icon: 'visibility', severity: 'suspicious' },
    ],
  },
  {
    id: 'alert-003',
    eventId: 'evt-003',
    eventType: 'suspicious_activity',
    cameraId: 'cam-009',
    cameraName: 'Cámara Interior A',
    storeId: 'store-005',
    storeName: 'Tienda Barranco',
    location: 'Pasillo central',
    severity: 'suspicious',
    status: 'acknowledged',
    leida: true,
    title: 'Aglomeración inusual en pasillo central',
    description: 'Se detectó una aglomeración atípica de personas en el pasillo central durante horario de baja afluencia.',
    createdAt: '2026-06-11T14:20:00',
    updatedAt: '2026-06-11T14:38:00',
    assignedTo: 'Agente López',
    evidence: [
      { id: 'ae-003a', type: 'image', label: 'Fotograma 14:20:00' },
      { id: 'ae-003b', type: 'video', label: 'Clip 45s', durationSeconds: 45 },
    ],
    timeline: [
      { timestamp: '2026-06-11T14:20:00', action: 'Alerta generada por actividad sospechosa', actor: 'Sistema VISORA', icon: 'notifications' },
      { timestamp: '2026-06-11T14:20:03', action: 'Notificación enviada a Agente López', actor: 'Sistema VISORA', icon: 'send' },
      { timestamp: '2026-06-11T14:38:00', action: 'Alerta reconocida — en seguimiento', actor: 'Agente López', icon: 'done' },
    ],
    recommendedActions: [
      { label: 'Revisar contexto del evento en video', icon: 'search', severity: 'normal' },
      { label: 'Monitorear dispersión del grupo', icon: 'visibility', severity: 'suspicious' },
    ],
  },
  {
    id: 'alert-004',
    eventId: 'evt-004',
    eventType: 'facial_recognition',
    cameraId: 'cam-002',
    cameraName: 'Cámara Caja Registradora',
    storeId: 'store-001',
    storeName: 'Tienda Miraflores',
    location: 'Zona de cajas',
    severity: 'normal',
    status: 'resolved',
    leida: true,
    title: 'Reconocimiento facial completado sin incidencias',
    description: 'Reconocimiento facial exitoso. Persona identificada no figura en ninguna lista de seguimiento.',
    createdAt: '2026-06-11T14:15:30',
    updatedAt: '2026-06-11T14:18:00',
    resolvedAt: '2026-06-11T14:18:00',
    evidence: [
      { id: 'ae-004a', type: 'image', label: 'Fotograma 14:15:30' },
    ],
    timeline: [
      { timestamp: '2026-06-11T14:15:30', action: 'Alerta generada por reconocimiento facial', actor: 'Sistema VISORA', icon: 'notifications' },
      { timestamp: '2026-06-11T14:15:33', action: 'Verificación automática completada', actor: 'Sistema VISORA', icon: 'verified' },
      { timestamp: '2026-06-11T14:18:00', action: 'Alerta resuelta automáticamente — sin riesgo', actor: 'Sistema VISORA', icon: 'check_circle' },
    ],
    recommendedActions: [],
  },
  {
    id: 'alert-005',
    eventId: 'evt-005',
    eventType: 'suspicious_activity',
    cameraId: 'cam-004',
    cameraName: 'Cámara Entrada Sur',
    storeId: 'store-002',
    storeName: 'Tienda San Isidro',
    location: 'Entrada lateral sur',
    severity: 'critical',
    status: 'open',
    leida: false,
    title: 'Posible intrusión fuera de horario comercial',
    description: 'Movimiento humano detectado a las 02:47 AM, fuera del horario comercial. Alta probabilidad de intrusión no autorizada.',
    createdAt: '2026-06-11T02:47:15',
    assignedTo: 'Jefe de Seguridad',
    evidence: [
      { id: 'ae-005a', type: 'image', label: 'Fotograma 02:47:15' },
      { id: 'ae-005b', type: 'video', label: 'Clip 60s', durationSeconds: 60 },
    ],
    timeline: [
      { timestamp: '2026-06-11T02:47:15', action: 'Alerta crítica generada — movimiento fuera de horario', actor: 'Sistema VISORA', icon: 'notifications' },
      { timestamp: '2026-06-11T02:47:18', action: 'Notificación urgente enviada a Jefe de Seguridad', actor: 'Sistema VISORA', icon: 'send' },
      { timestamp: '2026-06-11T02:47:20', action: 'Alerta escalada a protocolo de intrusión', actor: 'Sistema VISORA', icon: 'warning' },
    ],
    recommendedActions: [
      { label: 'Contactar a policía inmediatamente', icon: 'local_police', severity: 'critical' },
      { label: 'Activar alarma de seguridad', icon: 'alarm', severity: 'critical' },
      { label: 'Notificar al propietario de la tienda', icon: 'phone', severity: 'suspicious' },
    ],
  },
  {
    id: 'alert-006',
    eventId: 'evt-006',
    eventType: 'system',
    cameraId: 'cam-008',
    cameraName: 'Cámara Frente de Tienda',
    storeId: 'store-004',
    storeName: 'Tienda Callao',
    location: 'Fachada exterior',
    severity: 'normal',
    status: 'resolved',
    leida: true,
    title: 'Verificación periódica del sistema completada',
    description: 'Chequeo automático del sistema realizado. Todos los módulos operativos sin anomalías.',
    createdAt: '2026-06-11T13:00:00',
    resolvedAt: '2026-06-11T13:00:05',
    evidence: [],
    timeline: [
      { timestamp: '2026-06-11T13:00:00', action: 'Verificación periódica iniciada', actor: 'Sistema VISORA', icon: 'settings' },
      { timestamp: '2026-06-11T13:00:05', action: 'Verificación completada — sin anomalías', actor: 'Sistema VISORA', icon: 'check_circle' },
    ],
    recommendedActions: [],
  },
  {
    id: 'alert-007',
    eventId: 'evt-007',
    eventType: 'facial_recognition',
    cameraId: 'cam-010',
    cameraName: 'Cámara Interior B',
    storeId: 'store-005',
    storeName: 'Tienda Barranco',
    location: 'Zona premium',
    severity: 'suspicious',
    status: 'open',
    leida: false,
    title: 'Identificación facial fallida — rostro cubierto',
    description: 'El sistema no pudo completar la identificación debido a que el individuo tenía el rostro parcialmente cubierto. Confianza insuficiente.',
    createdAt: '2026-06-11T13:55:22',
    assignedTo: 'Supervisora Rivas',
    evidence: [
      { id: 'ae-007a', type: 'image', label: 'Fotograma 13:55:22' },
    ],
    timeline: [
      { timestamp: '2026-06-11T13:55:22', action: 'Alerta generada — identificación facial fallida', actor: 'Sistema VISORA', icon: 'notifications' },
      { timestamp: '2026-06-11T13:55:25', action: 'Notificación enviada a Supervisora Rivas', actor: 'Sistema VISORA', icon: 'send' },
    ],
    recommendedActions: [
      { label: 'Revisar video manualmente', icon: 'videocam', severity: 'suspicious' },
      { label: 'Solicitar identificación en caja si procede', icon: 'badge', severity: 'normal' },
    ],
  },
  {
    id: 'alert-008',
    eventId: 'evt-008',
    eventType: 'weapon_detection',
    cameraId: 'cam-012',
    cameraName: 'Cámara Bodega',
    storeId: 'store-007',
    storeName: 'Tienda Chorrillos',
    location: 'Bodega trasera',
    severity: 'suspicious',
    status: 'resolved',
    leida: true,
    title: 'Posible objeto contundente — revisión manual completada',
    description: 'Detección de posible objeto contundente con confianza media. Revisión manual confirmó que se trata de herramienta de trabajo.',
    createdAt: '2026-06-11T11:42:08',
    updatedAt: '2026-06-11T12:00:00',
    resolvedAt: '2026-06-11T12:05:00',
    assignedTo: 'Agente Vega',
    evidence: [
      { id: 'ae-008a', type: 'image', label: 'Fotograma 11:42:08' },
      { id: 'ae-008b', type: 'video', label: 'Clip 20s', durationSeconds: 20 },
    ],
    timeline: [
      { timestamp: '2026-06-11T11:42:08', action: 'Alerta generada por detección de objeto', actor: 'Sistema VISORA', icon: 'notifications' },
      { timestamp: '2026-06-11T11:42:12', action: 'Notificación enviada a Agente Vega', actor: 'Sistema VISORA', icon: 'send' },
      { timestamp: '2026-06-11T12:00:00', action: 'Alerta reconocida — revisión manual en curso', actor: 'Agente Vega', icon: 'done' },
      { timestamp: '2026-06-11T12:05:00', action: 'Alerta resuelta — falso positivo (herramienta de trabajo)', actor: 'Agente Vega', icon: 'check_circle' },
    ],
    recommendedActions: [
      { label: 'Verificar con supervisor de bodega', icon: 'person', severity: 'suspicious' },
    ],
  },
  {
    id: 'alert-009',
    eventId: 'evt-009',
    eventType: 'facial_recognition',
    cameraId: 'cam-001',
    cameraName: 'Cámara Entrada Principal',
    storeId: 'store-001',
    storeName: 'Tienda Miraflores',
    location: 'Entrada principal',
    severity: 'normal',
    status: 'resolved',
    leida: true,
    title: 'Acceso de empleado autorizado registrado',
    description: 'Reconocimiento facial exitoso de empleado registrado (EMP-015). Acceso autorizado confirmado automáticamente.',
    createdAt: '2026-06-11T09:05:11',
    resolvedAt: '2026-06-11T09:05:14',
    evidence: [
      { id: 'ae-009a', type: 'image', label: 'Fotograma 09:05:11' },
    ],
    timeline: [
      { timestamp: '2026-06-11T09:05:11', action: 'Reconocimiento facial iniciado', actor: 'Sistema VISORA', icon: 'face' },
      { timestamp: '2026-06-11T09:05:12', action: 'Empleado EMP-015 identificado correctamente', actor: 'Sistema VISORA', icon: 'verified' },
      { timestamp: '2026-06-11T09:05:14', action: 'Alerta resuelta — acceso autorizado registrado', actor: 'Sistema VISORA', icon: 'check_circle' },
    ],
    recommendedActions: [],
  },
  {
    id: 'alert-010',
    eventId: 'evt-010',
    eventType: 'suspicious_activity',
    cameraId: 'cam-005',
    cameraName: 'Cámara Sala Principal',
    storeId: 'store-002',
    storeName: 'Tienda San Isidro',
    location: 'Sala de ventas',
    severity: 'critical',
    status: 'acknowledged',
    leida: true,
    title: 'Comportamiento evasivo crítico detectado',
    description: 'Individuo esquiva sistemáticamente las cámaras de seguridad. Comportamiento altamente sospechoso catalogado como crítico.',
    createdAt: '2026-06-11T16:10:33',
    updatedAt: '2026-06-11T16:15:00',
    assignedTo: 'Jefe de Seguridad',
    evidence: [
      { id: 'ae-010a', type: 'image', label: 'Fotograma 16:10:33' },
      { id: 'ae-010b', type: 'video', label: 'Clip 90s', durationSeconds: 90 },
    ],
    timeline: [
      { timestamp: '2026-06-11T16:10:33', action: 'Alerta crítica generada por comportamiento evasivo', actor: 'Sistema VISORA', icon: 'notifications' },
      { timestamp: '2026-06-11T16:10:36', action: 'Notificación urgente enviada a Jefe de Seguridad', actor: 'Sistema VISORA', icon: 'send' },
      { timestamp: '2026-06-11T16:15:00', action: 'Alerta reconocida — equipo de seguridad en posición', actor: 'Jefe de Seguridad', icon: 'done' },
    ],
    recommendedActions: [
      { label: 'Alertar a seguridad en piso de sala', icon: 'security', severity: 'critical' },
      { label: 'Activar seguimiento multi-cámara', icon: 'videocam', severity: 'suspicious' },
      { label: 'Generar reporte de incidente', icon: 'description', severity: 'normal' },
    ],
  },
  {
    id: 'alert-011',
    eventId: 'evt-011',
    eventType: 'system',
    cameraId: 'cam-004',
    cameraName: 'Cámara Entrada Sur',
    storeId: 'store-002',
    storeName: 'Tienda San Isidro',
    location: 'Entrada lateral sur',
    severity: 'normal',
    status: 'resolved',
    leida: true,
    title: 'Reinicio automático de cámara completado',
    description: 'La cámara completó su ciclo de reinicio programado. Sistema operativo sin pérdida de datos.',
    createdAt: '2026-06-11T08:00:00',
    resolvedAt: '2026-06-11T08:00:45',
    evidence: [],
    timeline: [
      { timestamp: '2026-06-11T08:00:00', action: 'Reinicio de cámara iniciado', actor: 'Sistema VISORA', icon: 'restart_alt' },
      { timestamp: '2026-06-11T08:00:45', action: 'Cámara operativa — alerta resuelta automáticamente', actor: 'Sistema VISORA', icon: 'check_circle' },
    ],
    recommendedActions: [],
  },
  {
    id: 'alert-012',
    eventId: 'evt-012',
    eventType: 'suspicious_activity',
    cameraId: 'cam-009',
    cameraName: 'Cámara Interior A',
    storeId: 'store-005',
    storeName: 'Tienda Barranco',
    location: 'Pasillo central',
    severity: 'suspicious',
    status: 'open',
    leida: false,
    title: 'Permanencia estática prolongada en zona de alta rotación',
    description: 'Cliente lleva más de 15 minutos estático en zona de alta rotación sin realizar ninguna actividad de compra evidente.',
    createdAt: '2026-06-11T15:45:00',
    assignedTo: 'Agente López',
    evidence: [
      { id: 'ae-012a', type: 'image', label: 'Fotograma 15:45:00' },
    ],
    timeline: [
      { timestamp: '2026-06-11T15:45:00', action: 'Alerta generada — permanencia atípica detectada', actor: 'Sistema VISORA', icon: 'notifications' },
      { timestamp: '2026-06-11T15:45:03', action: 'Notificación enviada a Agente López', actor: 'Sistema VISORA', icon: 'send' },
    ],
    recommendedActions: [
      { label: 'Asignar empleado para atención al cliente', icon: 'person', severity: 'normal' },
      { label: 'Monitorear comportamiento continuamente', icon: 'visibility', severity: 'suspicious' },
    ],
  },
];
