import type { Camera } from '../../core/models/camera.model';

export const MOCK_CAMERAS: Camera[] = [
  {
    id: 'cam-001',
    name: 'Cámara Entrada Principal',
    storeId: 'store-001',
    storeName: 'Tienda Miraflores',
    location: 'Entrada principal',
    ipUrl: '192.168.1.101',
    resolution: '1080p',
    status: 'online',
    capabilities: { facialRecognition: true, weaponDetection: true, recording: true },
    lastEvent: 'Persona detectada',
    lastEventTime: '14:32',
    createdAt: '2024-01-10',
    notes: 'Cámara principal de vigilancia. Cobertura 180°.',
  },
  {
    id: 'cam-002',
    name: 'Cámara Caja Registradora',
    storeId: 'store-001',
    storeName: 'Tienda Miraflores',
    location: 'Zona de cajas',
    ipUrl: '192.168.1.102',
    resolution: '1080p',
    status: 'online',
    capabilities: { facialRecognition: true, weaponDetection: false, recording: true },
    lastEvent: 'Transacción registrada',
    lastEventTime: '14:28',
    createdAt: '2024-01-10',
  },
  {
    id: 'cam-003',
    name: 'Cámara Almacén',
    storeId: 'store-001',
    storeName: 'Tienda Miraflores',
    location: 'Almacén interior',
    ipUrl: '192.168.1.103',
    resolution: '720p',
    status: 'offline',
    capabilities: { facialRecognition: false, weaponDetection: false, recording: true },
    createdAt: '2024-01-12',
    notes: 'Revisión pendiente. Sin señal desde las 13:00.',
  },
  {
    id: 'cam-004',
    name: 'Cámara Entrada Sur',
    storeId: 'store-002',
    storeName: 'Tienda San Isidro',
    location: 'Entrada lateral sur',
    ipUrl: '192.168.2.101',
    resolution: '1080p',
    status: 'online',
    capabilities: { facialRecognition: true, weaponDetection: true, recording: true },
    lastEvent: 'Alerta de movimiento',
    lastEventTime: '14:45',
    createdAt: '2024-02-01',
  },
  {
    id: 'cam-005',
    name: 'Cámara Sala Principal',
    storeId: 'store-002',
    storeName: 'Tienda San Isidro',
    location: 'Sala de ventas',
    ipUrl: '192.168.2.102',
    resolution: '4K',
    status: 'online',
    capabilities: { facialRecognition: true, weaponDetection: true, recording: true },
    lastEvent: 'Persona reconocida',
    lastEventTime: '14:40',
    createdAt: '2024-02-01',
    notes: 'Alta prioridad. Zona de mayor tráfico.',
  },
  {
    id: 'cam-006',
    name: 'Cámara Parking',
    storeId: 'store-003',
    storeName: 'Tienda Surco',
    location: 'Estacionamiento exterior',
    ipUrl: '192.168.3.101',
    resolution: '1080p',
    status: 'error',
    capabilities: { facialRecognition: false, weaponDetection: false, recording: true },
    createdAt: '2024-02-15',
    notes: 'Error de firmware. Pendiente actualización.',
  },
  {
    id: 'cam-007',
    name: 'Cámara Probadores',
    storeId: 'store-003',
    storeName: 'Tienda Surco',
    location: 'Zona de probadores',
    ipUrl: '192.168.3.102',
    resolution: '720p',
    status: 'maintenance',
    capabilities: { facialRecognition: false, weaponDetection: false, recording: false },
    createdAt: '2024-02-15',
    notes: 'En mantenimiento preventivo programado.',
  },
  {
    id: 'cam-008',
    name: 'Cámara Frente de Tienda',
    storeId: 'store-004',
    storeName: 'Tienda Callao',
    location: 'Fachada exterior',
    ipUrl: '192.168.4.101',
    resolution: '1080p',
    status: 'online',
    capabilities: { facialRecognition: true, weaponDetection: true, recording: true },
    lastEvent: 'Sin novedad',
    lastEventTime: '14:50',
    createdAt: '2024-03-01',
  },
  {
    id: 'cam-009',
    name: 'Cámara Interior A',
    storeId: 'store-005',
    storeName: 'Tienda Barranco',
    location: 'Pasillo central',
    ipUrl: '192.168.5.101',
    resolution: '1080p',
    status: 'online',
    capabilities: { facialRecognition: true, weaponDetection: false, recording: true },
    lastEvent: 'Aglomeración detectada',
    lastEventTime: '14:20',
    createdAt: '2024-03-10',
  },
  {
    id: 'cam-010',
    name: 'Cámara Interior B',
    storeId: 'store-005',
    storeName: 'Tienda Barranco',
    location: 'Zona premium',
    ipUrl: '192.168.5.102',
    resolution: '4K',
    status: 'online',
    capabilities: { facialRecognition: true, weaponDetection: true, recording: true },
    lastEvent: 'Sin novedad',
    lastEventTime: '14:55',
    createdAt: '2024-03-10',
  },
  {
    id: 'cam-011',
    name: 'Cámara Recepción',
    storeId: 'store-006',
    storeName: 'Tienda La Molina',
    location: 'Área de recepción',
    ipUrl: '192.168.6.101',
    resolution: '1080p',
    status: 'offline',
    capabilities: { facialRecognition: false, weaponDetection: false, recording: true },
    createdAt: '2024-03-20',
    notes: 'Desconectada por mantenimiento de red.',
  },
  {
    id: 'cam-012',
    name: 'Cámara Bodega',
    storeId: 'store-007',
    storeName: 'Tienda Chorrillos',
    location: 'Bodega trasera',
    ipUrl: '192.168.7.101',
    resolution: '720p',
    status: 'online',
    capabilities: { facialRecognition: false, weaponDetection: true, recording: true },
    lastEvent: 'Sin novedad',
    lastEventTime: '13:45',
    createdAt: '2024-04-01',
  },
];
