import type { Store } from '../../core/models/store.model';

export const MOCK_STORES: Store[] = [
  {
    id: '1',
    name: 'Tienda Miraflores Centro',
    address: 'Av. Larco 234, Piso 2',
    city: 'Miraflores',
    status: 'active',
    cameraCount: 12,
    createdAt: '2024-03-10',
    manager: 'Carlos Mendoza',
    email: 'c.mendoza@visora.pe',
    phone: '+51 987 654 321',
    notes:
      'Tienda principal de la zona de Miraflores. Cuenta con acceso biométrico en la entrada principal.',
  },
  {
    id: '2',
    name: 'Tienda San Isidro',
    address: 'Calle Las Begonias 521',
    city: 'San Isidro',
    status: 'active',
    cameraCount: 8,
    createdAt: '2024-04-05',
    manager: 'María Quispe',
    email: 'm.quispe@visora.pe',
    phone: '+51 976 543 210',
    notes: '',
  },
  {
    id: '3',
    name: 'Tienda Surco Principal',
    address: 'Av. Javier Prado Este 3200',
    city: 'Santiago de Surco',
    status: 'active',
    cameraCount: 15,
    createdAt: '2024-01-20',
    manager: 'José Torres',
    email: 'j.torres@visora.pe',
    phone: '+51 965 432 109',
    notes:
      'Sede con mayor flujo de clientes. Requiere revisión periódica de las cámaras del patio trasero.',
  },
  {
    id: '4',
    name: 'Tienda Callao Norte',
    address: 'Jr. Inca 456',
    city: 'Callao',
    status: 'inactive',
    cameraCount: 6,
    createdAt: '2024-05-12',
    manager: 'Ana Flores',
    email: 'a.flores@visora.pe',
    phone: '+51 954 321 098',
    notes: 'Temporalmente cerrada por refacción del local.',
  },
  {
    id: '5',
    name: 'Tienda Barranco',
    address: 'Av. Grau 189, Loc. 3',
    city: 'Barranco',
    status: 'active',
    cameraCount: 9,
    createdAt: '2024-02-28',
    manager: 'Luis Ramírez',
    email: 'l.ramirez@visora.pe',
    phone: '+51 943 210 987',
    notes: '',
  },
  {
    id: '6',
    name: 'Tienda La Molina',
    address: 'Av. La Molina 1500',
    city: 'La Molina',
    status: 'active',
    cameraCount: 11,
    createdAt: '2024-06-01',
    manager: 'Patricia Vera',
    email: 'p.vera@visora.pe',
    phone: '+51 932 109 876',
    notes: '',
  },
  {
    id: '7',
    name: 'Tienda Chorrillos Sur',
    address: 'Av. Defensores del Morro 800',
    city: 'Chorrillos',
    status: 'inactive',
    cameraCount: 4,
    createdAt: '2023-12-15',
    manager: 'Roberto Chávez',
    email: 'r.chavez@visora.pe',
    phone: '+51 921 098 765',
    notes: 'Local en proceso de reactivación. Pendiente revisión técnica de cámaras.',
  },
  {
    id: '8',
    name: 'Tienda Lince',
    address: 'Av. Iquitos 1240',
    city: 'Lince',
    status: 'active',
    cameraCount: 7,
    createdAt: '2024-07-08',
    manager: 'Sofía Díaz',
    email: 's.diaz@visora.pe',
    phone: '+51 910 987 654',
    notes: '',
  },
];
